name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83e840a13014dc6bb65c4e2338ae4f2ad72a8b5cb8ddba251aabe0a3dd6fcc73"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
