name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3a715ed485c8d85951b339303ad8126d9721b5be2dc5aad783a7c09c00300dd"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
