name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a8ea6f86f2fac27f4827a4f03313491bb284da49200eef266c6f8a91fc75bd9"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
