name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20c814626dc838b494fb49855c3028b559d4d9fef1a5da503cbfaea60b43cad6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
