name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8256080ef7d4946ed97c0bf3bcbf9e96be7e584642d57d08cb7473240661a98a"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
