name = "Reereum"
author = "FlashyReese"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16311a8e39f19f1b62a0981a2a80ca57bc79c5efb1975cfa13cff6ea4380621b"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
