name = "Reereum"
author = "FlashyReese"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c275f8c18b7d2b3d560bdf4820ed138117259311bbc32ccd42a58d1c575981a"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
