name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5bee9dd947e3c888aebf619a9af665d2852913912ec97481790c42dcbe48996"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
