name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1e1ce421dff61d55b2ac4f975a04712a4429020736305e73b7f9cda5f7dab25"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
