name = "Reereum"
author = "FlashyReese"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88ae5ef18ca79860d9657d675712b03490aa44ddb27e74b1be3a36dcda364925"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
