name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72cc58fb6093c47261f6a8b98e069014b24491f0299400bc6fa380f27beda47a"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
