name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a4a89847e5a16112f4c18becef9a2407ffa42d447c9e691579a47ef4d8e4bf2"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
