name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f96db46085a0e0fefd0f8972a94c4183995a23aa153e10809ec579877d5f42b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
