name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0c0bd8c3eb48b6d3e59d6f6f394c3c891572e99ceaf7a7a308a2eff8503aaff"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
