name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "563f8f22ce9351b666eb973f03c2954c744961557b62d3cad40e7b2f43ceb248"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
