name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f03a7b64f2a1b42aea58ffb5af07594bb3816fa59c5770edf0e59c49c0b1fd19"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
