name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74838b660d8dfca22e19fc14c911c86dd3eea33d0e8ff755cef373a68b2d9933"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
