name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0a07bf5be15e4ad9f4c9528fbc6d24841ead4fac631b5a3490f4516f3e19843"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
