name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "387c71ba9ef7895533a1d6f57bdd99bf357c8d48430b37dedd6f1a19b7c4218c"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
