name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2348c734a871dc6a24b7c00176241481e012d1baaaa3ac5b2c0842a2146f83b"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
