name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fcc74aea6eb69873da21933268c294bd7e84f1fc4b5f85db3c00805a98eafcc"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
