name = "Reereum"
author = "FlashyReese"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a911e866cef5c28e982327caa9e0c802558870823f60613f66dba152b6f0f591"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
