name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71ebf6625b1fbe92222b3479301de844219b9d03ab3af495f4106a6f40ad9523"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
