name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72e0baa25a27f9090fd6c3f04c47543b03d47dcaa9d47d60e6c282ceea1a20a"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
