name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4ea0429be19e43bcb53b240b9b4afbd13005c9212dfa9d321ed35f65b62fe07"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
