name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f12b9cbaafd3f58a1aba23842d0ac43fdbcde6c034c5925aa6c84ce50114f2f"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
