name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a92a7dd2d7d1a55c60676d6bdf19409bfc369c9074c2ec09269f05ebde108a"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
