name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e64541ffc9e6d0ed652ef4944709b137405ce62b340f88ece74ec4ea615bf8af"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
