name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea9723a634f5d77ea1c35a04253a11597fac0f3fb350dc41ba20ef6dca184338"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
