name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26d48af0bf2a71086a1421c130db3ed37b28a548015fda001926dd46711ab24d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
