name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef36b773d65c8e7fc3e643557c3825383e8e6b555c06752e04ad08ef9445b8b1"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
