name = "Reereum"
author = "FlashyReese"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54a6fdcbf046e380ecb003032f362300a04405819ec1d72b9c8cae0b99191483"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
