name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ce488e269f6dded8d880ab57a8d3e9f704ae43d31c66cd667f86cc2d51ee133"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
