name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91a388a47bc82690a6448099f98c3931b51ff7bab8e3a160b9ca5d3ac378684f"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
