name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d598dbce2c7f624c9cec4f369cdf5e87e2bdac73baf4a44d693a171fd8fcec4"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
