name = "Reereum"
author = "FlashyReese"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83b61a9725a8e8ddcc9198b9a07375190574bfa09e04bc24946cf5ecbaa92b62"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
