name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c58752e8ab1c748b8427ab153793b3c4eec1efd14d6e7e768f312d6dae74b69"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
