name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e429674c56712f2881ed8caff11be73253fe5460d9355f6a0a0c7a100470afeb"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
