name = "Reereum"
author = "FlashyReese"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a97f3ffbe8f7b995d5225c51ec914a77365d1024e16d0d13f963b4dd37c8ad"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
