name = "Reereum"
author = "FlashyReese"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "183fcfaebe3b769abc94aa3564655a4fb1b98bc416646a1ffb965df40fa1768f"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
