name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a4200fbee5604989e6affe4d4ce2165fd7dd272cf9706cfbf7e661761ce40fd"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
