name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2a4feec7d3edaadffd4b68df619232092c9eba59437d7e0049b5552e4c6b15"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
