name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4fcfb91080588452e1d01d704d4147f113b99f8be7da5b66b6f0c8661fcb37"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
