name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c2f5070d6c4f8836ece58ec9fe1ba0dc0163e4053c94cd329d83acc87c47fa"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
