name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3b441e3a5c002d4868be97e6a74fafa2bdeab09f7d8f0c373d9fb5e8f97c147"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
