name = "Reereum"
author = "FlashyReese"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "232d7fbccc181c3c7d7e62ae5afd60487207fbebbfefbcc55a7e662ff1380e29"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
