name = "Reereum"
author = "FlashyReese"
version = "0.8.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4097f6fd0937a809d8ebd73029c0bc00a6d7f295839fc1a840721c9fc17ee653"

[versions]
fabric = "0.11.3"
minecraft = "1.17"
