name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6168d68dba1b728a154e46e753d1b8df91f7fccb00afd51246388bc68fe4f59"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
