name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f69be769d8a5ad78f099185066b5919142f9f3e45862392b0ea4a6d6fa7c946d"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
