name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faeb3d1b0d51824e87964f66e04a456193df0e69ff68609476cf15d28efde545"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
