name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93a28bc9e91a216d8cbbb74c76b741d76f199bc3270eb5f691e9b271c680ca8b"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
