name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6482b7707ca7255b48d9ae3a8f2970042badb19ef292375e6c26d79f8deb7346"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
