name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c40ab44803b92ef02ca76447d2765649214ee52cd3b2ee0cca92dcb5375222"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
