name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a365de221f8ce09730082686a4f17f9808ccf3ded4c8b8c0bcf1cb2543457e8c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
