name = "Reereum"
author = "FlashyReese"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "814da9167d0d0e8848edfee8460288fa194d90c671d9906cb1ba1babedadb0a4"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
