name = "Reereum"
author = "FlashyReese"
version = "0.7.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4df830ad8d7401277cffefb014ee0132c74fa74df82ae1dc8ce146783c41c47"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
