name = "Reereum"
author = "FlashyReese"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22ec9b8df56e670a64f61019b1cb8e93c741b410dd63728a1fef616f82a5b5f0"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
