name = "Reereum"
author = "FlashyReese"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c19bf430f52c3dad51912533f1308ff443b0a73f4c89c1bf7c4c3f8d1dcebe5"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
