name = "Architectury API (Fabric)"
filename = "architectury-2.4.26-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3436/837/architectury-2.4.26-fabric.jar"
hash-format = "murmur2"
hash = "2442818780"

[update]
[update.curseforge]
file-id = 3436837
project-id = 419697
release-channel = "beta"
