name = "Architectury API (Fabric)"
filename = "architectury-1.12.145-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3279/825/architectury-1.12.145-fabric.jar"
hash-format = "murmur2"
hash = "1618563718"

[update]
[update.curseforge]
file-id = 3279825
project-id = 419697
release-channel = "beta"
