name = "Architectury API (Fabric)"
filename = "architectury-3.7.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/9/architectury-3.7.20.jar"
hash-format = "murmur2"
hash = "805413362"

[update]
[update.curseforge]
file-id = 3652009
project-id = 419697
release-channel = "beta"
