name = "Architectury API (Fabric)"
filename = "architectury-2.0.8-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/439/architectury-2.0.8-fabric.jar"
hash-format = "murmur2"
hash = "4202710156"

[update]
[update.curseforge]
file-id = 3346439
project-id = 419697
release-channel = "beta"
