name = "Architectury API (Fabric)"
filename = "architectury-2.1.20-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3376/69/architectury-2.1.20-fabric.jar"
hash-format = "murmur2"
hash = "4292595446"

[update]
[update.curseforge]
file-id = 3376069
project-id = 419697
release-channel = "beta"
