name = "Architectury API (Fabric)"
filename = "architectury-2.0.7-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/651/architectury-2.0.7-fabric.jar"
hash-format = "murmur2"
hash = "1933849112"

[update]
[update.curseforge]
file-id = 3343651
project-id = 419697
release-channel = "beta"
