name = "Architectury API (Fabric)"
filename = "architectury-2.4.25-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3427/341/architectury-2.4.25-fabric.jar"
hash-format = "murmur2"
hash = "2890777915"

[update]
[update.curseforge]
file-id = 3427341
project-id = 419697
release-channel = "beta"
