name = "Architectury API (Fabric)"
filename = "architectury-2.9.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/386/architectury-2.9.3.jar"
hash-format = "murmur2"
hash = "2480832049"

[update]
[update.curseforge]
file-id = 3587386
project-id = 419697
release-channel = "beta"
