name = "Architectury API (Fabric)"
filename = "architectury-3.7.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/981/architectury-3.7.22.jar"
hash-format = "murmur2"
hash = "1687714073"

[update]
[update.curseforge]
file-id = 3652981
project-id = 419697
release-channel = "beta"
