name = "Architectury API (Fabric)"
filename = "architectury-2.0.10-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/435/architectury-2.0.10-fabric.jar"
hash-format = "murmur2"
hash = "4241629302"

[update]
[update.curseforge]
file-id = 3358435
project-id = 419697
release-channel = "beta"
