name = "Architectury API (Fabric)"
filename = "architectury-2.0.9-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/375/architectury-2.0.9-fabric.jar"
hash-format = "murmur2"
hash = "3599393402"

[update]
[update.curseforge]
file-id = 3351375
project-id = 419697
release-channel = "beta"
