name = "Better Biome Blend"
filename = "betterbiomeblend-1.18.2-1.3.4-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3692/463/betterbiomeblend-1.18.2-1.3.4-fabric.jar"
hash-format = "sha1"
hash = "2f715623b5d50b1f3c62d7c9ba89fd564078ba53"

[update]
[update.curseforge]
file-id = 3692463
project-id = 446253
