name = "Better Biome Blend"
filename = "betterbiomeblend-1.18.2-1.3.5-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "65f2441618ab91a4b0c174b3bfbde89f894b3cba"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3804087
project-id = 446253
