name = "Blur (Fabric)"
filename = "Blur-2.2.0-1.17+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3359/799/Blur-2.2.0-1.17+fabric.jar"
hash-format = "murmur2"
hash = "1382073908"

[update]
[update.curseforge]
file-id = 3359799
project-id = 393563
release-channel = "beta"
