name = "Blur (Fabric)"
filename = "Blur-2.1.0-21w08b+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3227/468/Blur-2.1.0-21w08b+fabric.jar"
hash-format = "murmur2"
hash = "4287064914"

[update]
[update.curseforge]
file-id = 3227468
project-id = 393563
release-channel = "beta"
