name = "Blur (Fabric)"
filename = "blur-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3510/590/blur-2.4.0.jar"
hash-format = "murmur2"
hash = "3326430759"

[update]
[update.curseforge]
file-id = 3510590
project-id = 393563
