name = "Blur (Fabric)"
filename = "Blur-2.2.1-1.17+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3359/936/Blur-2.2.1-1.17+fabric.jar"
hash-format = "murmur2"
hash = "905546928"

[update]
[update.curseforge]
file-id = 3359936
project-id = 393563
release-channel = "beta"
