name = "Bobby"
filename = "bobby-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3251/276/bobby-1.1.4.jar"
hash-format = "murmur2"
hash = "1484381371"

[update]
[update.curseforge]
file-id = 3251276
project-id = 409301
release-channel = "beta"
