name = "Borderless Mining"
filename = "borderless-mining-1.1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/245/borderless-mining-1.1.1+1.18.jar"
hash-format = "murmur2"
hash = "749412091"

[update]
[update.curseforge]
file-id = 3549245
project-id = 310205
