name = "Borderless Mining"
filename = "borderless-mining-1.1.2+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/145/borderless-mining-1.1.2+1.18.2.jar"
hash-format = "sha1"
hash = "2a7490d56d040529c86e0d1e4017cb825381bf78"

[update]
[update.curseforge]
file-id = 3755145
project-id = 310205
