name = "Chime (Fabric)"
filename = "chime-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3285/347/chime-1.1.3.jar"
hash-format = "murmur2"
hash = "3096808552"

[update]
[update.curseforge]
file-id = 3285347
project-id = 432776
