name = "Cloth Config API (Fabric)"
filename = "cloth-config-5.2.47-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/636/cloth-config-5.2.47-fabric.jar"
hash-format = "murmur2"
hash = "4189760986"

[update]
[update.curseforge]
file-id = 3559636
project-id = 319057
