name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.14.54-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3641/84/cloth-config-4.14.54-fabric.jar"
hash-format = "sha1"
hash = "c9ed6fb0dd606543af9d89e34f21bfdbeebd63a0"

[update]
[update.curseforge]
file-id = 3641084
project-id = 319057
