name = "Cloth Config API (Fabric)"
filename = "cloth-config-5.0.37-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3409/421/cloth-config-5.0.37-fabric.jar"
hash-format = "murmur2"
hash = "305610416"

[update]
[update.curseforge]
file-id = 3409421
project-id = 319057
release-channel = "beta"
