name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.13.49-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/633/cloth-config-4.13.49-fabric.jar"
hash-format = "murmur2"
hash = "178602638"

[update]
[update.curseforge]
file-id = 3559633
project-id = 319057
