name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.11.24-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3304/790/cloth-config-4.11.24-fabric.jar"
hash-format = "murmur2"
hash = "899675778"

[update]
[update.curseforge]
file-id = 3304790
project-id = 319057
release-channel = "beta"
