name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.11.18-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3253/619/cloth-config-4.11.18-fabric.jar"
hash-format = "murmur2"
hash = "1421953320"

[update]
[update.curseforge]
file-id = 3253619
project-id = 319057
release-channel = "beta"
