name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.11.15-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3235/777/cloth-config-4.11.15-fabric.jar"
hash-format = "murmur2"
hash = "3972118632"

[update]
[update.curseforge]
file-id = 3235777
project-id = 319057
release-channel = "beta"
