name = "Colormatic"
filename = "colormatic-2.2.8+mc.1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3166/863/colormatic-2.2.8+mc.1.16.3.jar"
hash-format = "murmur2"
hash = "3746856853"

[update]
[update.curseforge]
file-id = 3166863
project-id = 325092
release-channel = "beta"
