name = "Colormatic"
filename = "colormatic-2.2.10+mc.1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3436/738/colormatic-2.2.10+mc.1.17.1.jar"
hash-format = "murmur2"
hash = "350616487"

[update]
[update.curseforge]
file-id = 3436738
project-id = 325092
release-channel = "beta"
