name = "Colormatic"
filename = "colormatic-3.0.0+mc.1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/953/colormatic-3.0.0+mc.1.18.jar"
hash-format = "murmur2"
hash = "3053511537"

[update]
[update.curseforge]
file-id = 3591953
project-id = 325092
release-channel = "beta"
