name = "Colormatic"
filename = "colormatic-2.3.1+mc.1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3522/12/colormatic-2.3.1+mc.1.17.1.jar"
hash-format = "murmur2"
hash = "1191722569"

[update]
[update.curseforge]
file-id = 3522012
project-id = 325092
