name = "Colormatic"
filename = "colormatic-2.3.0+mc.1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3475/133/colormatic-2.3.0+mc.1.17.1.jar"
hash-format = "murmur2"
hash = "686398706"

[update]
[update.curseforge]
file-id = 3475133
project-id = 325092
release-channel = "beta"
