name = "Colormatic"
filename = "colormatic-2.2.9+mc.1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3356/722/colormatic-2.2.9+mc.1.16.5.jar"
hash-format = "murmur2"
hash = "2698887388"

[update]
[update.curseforge]
file-id = 3356722
project-id = 325092
release-channel = "beta"
