name = "Continuity"
filename = "continuity-1.0.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3472/479/continuity-1.0.0+1.17.jar"
hash-format = "murmur2"
hash = "2802689940"

[update]
[update.curseforge]
file-id = 3472479
project-id = 531351
release-channel = "beta"
