name = "Continuity"
filename = "continuity-1.0.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/420/continuity-1.0.3+1.18.jar"
hash-format = "murmur2"
hash = "2946885067"

[update]
[update.curseforge]
file-id = 3549420
project-id = 531351
release-channel = "beta"
