name = "Continuity"
filename = "continuity-1.0.3+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/414/continuity-1.0.3+1.17.jar"
hash-format = "murmur2"
hash = "2379446761"

[update]
[update.curseforge]
file-id = 3549414
project-id = 531351
