name = "Dark Loading Screen"
filename = "dark-loading-screen-1.6.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3429/378/dark-loading-screen-1.6.7.jar"
hash-format = "murmur2"
hash = "1988110727"

[update]
[update.curseforge]
file-id = 3429378
project-id = 365727
release-channel = "beta"
