name = "Dark Loading Screen"
filename = "dark-loading-screen-1.6.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3448/431/dark-loading-screen-1.6.9.jar"
hash-format = "murmur2"
hash = "3780522249"

[update]
[update.curseforge]
file-id = 3448431
project-id = 365727
release-channel = "beta"
