name = "Dynamic FPS"
filename = "dynamic-fps-2.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3356/224/dynamic-fps-2.0.4.jar"
hash-format = "murmur2"
hash = "2574305371"

[update]
[update.curseforge]
file-id = 3356224
project-id = 335493
release-channel = "beta"
