name = "Enhanced Block Entities"
filename = "enhancedblockentities-0.1--1.16.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/OVuFYfre/versions/0.1/enhancedblockentities-0.1--1.16.x.jar"
hash-format = "sha512"
hash = "e0425b863dbed993ef6bfc773bdec74d5d1d6a580bf9b315ba8afc944df4db53c5f69d84e872a81d94d18b103476a320b8f0979fd15f8581b161c7d77281f994"

[update]
[update.modrinth]
mod-id = "OVuFYfre"
version = "tUbREtJR"
