name = "Enhanced Block Entities"
filename = "enhancedblockentities-0.5+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3557/31/enhancedblockentities-0.5+1.18.jar"
hash-format = "murmur2"
hash = "138218904"

[update]
[update.curseforge]
file-id = 3557031
project-id = 452046
