name = "Fabric API"
filename = "fabric-api-0.32.9+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3276/155/fabric-api-0.32.9+1.16.jar"
hash-format = "murmur2"
hash = "3523458212"

[update]
[update.curseforge]
file-id = 3276155
project-id = 306612
release-channel = "beta"
