name = "Fabrishot"
filename = "fabrishot-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3271/155/fabrishot-1.4.0.jar"
hash-format = "murmur2"
hash = "1862084118"

[update]
[update.curseforge]
file-id = 3271155
project-id = 404870
