name = "Fabric API"
filename = "fabric-api-0.33.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/140/fabric-api-0.33.0+1.16.jar"
hash-format = "murmur2"
hash = "4081730892"

[update]
[update.curseforge]
file-id = 3281140
project-id = 306612
release-channel = "beta"
