name = "Fabric API"
filename = "fabric-api-0.34.10+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/352/fabric-api-0.34.10+1.17.jar"
hash-format = "murmur2"
hash = "330818842"

[update]
[update.curseforge]
file-id = 3346352
project-id = 306612
release-channel = "beta"
