name = "Fabric API"
filename = "fabric-api-0.32.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3232/20/fabric-api-0.32.0+1.16.jar"
hash-format = "murmur2"
hash = "1955862563"

[update]
[update.curseforge]
file-id = 3232020
project-id = 306612
release-channel = "beta"
