name = "Fabrishot"
filename = "fabrishot-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3381/995/fabrishot-1.5.1.jar"
hash-format = "murmur2"
hash = "165472990"

[update]
[update.curseforge]
file-id = 3381995
project-id = 404870
