name = "Fabric API"
filename = "fabric-api-0.36.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/614/fabric-api-0.36.0+1.16.jar"
hash-format = "murmur2"
hash = "4023689070"

[update]
[update.curseforge]
file-id = 3358614
project-id = 306612
release-channel = "beta"
