name = "Fabric API"
filename = "fabric-api-0.40.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/257/fabric-api-0.40.0+1.16.jar"
hash-format = "murmur2"
hash = "3728731531"

[update]
[update.curseforge]
file-id = 3446257
project-id = 306612
release-channel = "beta"
