name = "Fabrishot"
filename = "fabrishot-1.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/125/fabrishot-1.6.2.jar"
hash-format = "murmur2"
hash = "3236603504"

[update]
[update.curseforge]
file-id = 3637125
project-id = 404870
release-channel = "beta"
