name = "Fabric API"
filename = "fabric-api-0.34.6+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3324/592/fabric-api-0.34.6+1.16.jar"
hash-format = "murmur2"
hash = "552490856"

[update]
[update.curseforge]
file-id = 3324592
project-id = 306612
release-channel = "beta"
