name = "Fabric API"
filename = "fabric-api-0.53.0+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "9763a1588fe73c36a4d15f98d974240ec7e5ad6b"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3798283
project-id = 306612
