name = "Fabric API"
filename = "fabric-api-0.36.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/619/fabric-api-0.36.0+1.17.jar"
hash-format = "murmur2"
hash = "2284688134"

[update]
[update.curseforge]
file-id = 3358619
project-id = 306612
release-channel = "beta"
