name = "Fabric API"
filename = "fabric-api-0.40.6+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3483/905/fabric-api-0.40.6+1.16.jar"
hash-format = "murmur2"
hash = "433431115"

[update]
[update.curseforge]
file-id = 3483905
project-id = 306612
release-channel = "beta"
