name = "Fabric API"
filename = "fabric-api-0.34.0+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3295/264/fabric-api-0.34.0+1.16.jar"
hash-format = "murmur2"
hash = "2631043536"

[update]
[update.curseforge]
file-id = 3295264
project-id = 306612
release-channel = "beta"
