name = "Fabric API"
filename = "fabric-api-0.35.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3347/891/fabric-api-0.35.0+1.17.jar"
hash-format = "murmur2"
hash = "2957158952"

[update]
[update.curseforge]
file-id = 3347891
project-id = 306612
release-channel = "beta"
