name = "Fabric API"
filename = "fabric-api-0.37.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3398/557/fabric-api-0.37.1+1.17.jar"
hash-format = "murmur2"
hash = "2397743126"

[update]
[update.curseforge]
file-id = 3398557
project-id = 306612
release-channel = "beta"
