name = "Fabric API"
filename = "fabric-api-0.34.7+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/351/fabric-api-0.34.7+1.16.jar"
hash-format = "murmur2"
hash = "1054120191"

[update]
[update.curseforge]
file-id = 3346351
project-id = 306612
release-channel = "beta"
