name = "Fabric API"
filename = "fabric-api-0.38.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/313/fabric-api-0.38.1+1.17.jar"
hash-format = "murmur2"
hash = "1928106842"

[update]
[update.curseforge]
file-id = 3432313
project-id = 306612
release-channel = "beta"
