name = "Fabrishot"
filename = "fabrishot-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/922/fabrishot-1.6.0.jar"
hash-format = "murmur2"
hash = "1467117810"

[update]
[update.curseforge]
file-id = 3542922
project-id = 404870
release-channel = "beta"
