name = "Fabric API"
filename = "fabric-api-0.45.2+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/215/fabric-api-0.45.2+1.17.jar"
hash-format = "murmur2"
hash = "4095578016"

[update]
[update.curseforge]
file-id = 3595215
project-id = 306612
release-channel = "beta"
