name = "Fast Furnace for Fabric"
filename = "fastfurnace-1.18-4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3558/448/fastfurnace-1.18-4.jar"
hash-format = "murmur2"
hash = "1789020635"

[update]
[update.curseforge]
file-id = 3558448
project-id = 364540
release-channel = "beta"
