name = "Fast Furnace for Fabric"
filename = "fastfurnace-2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3264/245/fastfurnace-2.4.jar"
hash-format = "murmur2"
hash = "2866188287"

[update]
[update.curseforge]
file-id = 3264245
project-id = 364540
release-channel = "beta"
