name = "FerriteCore (Fabric)"
filename = "ferritecore-2.1.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3485/637/ferritecore-2.1.0-fabric.jar"
hash-format = "murmur2"
hash = "3244022036"

[update]
[update.curseforge]
file-id = 3485637
project-id = 459857
