name = "In-Game Account Switcher"
filename = "InGameAccountSwitcher-Fabric-1.18-7.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/107/InGameAccountSwitcher-Fabric-1.18-7.1.3.jar"
hash-format = "murmur2"
hash = "568024070"

[update]
[update.curseforge]
file-id = 3545107
project-id = 232676
