name = "In-Game Account Switcher"
filename = "InGameAccountSwitcher-Fabric-1.18-7.2.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "60586aa768ac80a7e85b4757b126d07751d7d6f1"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3827453
project-id = 232676
