name = "Indium"
filename = "indium-1.0.0+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3484/850/indium-1.0.0+mc1.16.5.jar"
hash-format = "murmur2"
hash = "287857057"

[update]
[update.curseforge]
file-id = 3484850
project-id = 459496
