name = "Indium"
filename = "indium-1.0.2-alpha1+mc1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/434/indium-1.0.2-alpha1+mc1.18.jar"
hash-format = "murmur2"
hash = "3058950694"

[update]
[update.curseforge]
file-id = 3542434
project-id = 459496
release-channel = "beta"
