name = "Indium"
filename = "indium-1.0.1+mc1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3535/202/indium-1.0.1+mc1.17.1.jar"
hash-format = "murmur2"
hash = "2442250681"

[update]
[update.curseforge]
file-id = 3535202
project-id = 459496
