name = "Iris Shaders"
filename = "iris-mc1.16.5-1.2.0-pre.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/852/iris-mc1.16.5-1.2.0-pre.jar"
hash-format = "murmur2"
hash = "1699418536"

[update]
[update.curseforge]
file-id = 3612852
project-id = 455508
