name = "Iris Shaders"
filename = "iris-mc1.17-1.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/381/iris-mc1.17-1.1.5.jar"
hash-format = "murmur2"
hash = "547095086"

[update]
[update.curseforge]
file-id = 3605381
project-id = 455508
