name = "Iris Shaders"
filename = "iris-mc1.17-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/180/iris-mc1.17-1.1.4.jar"
hash-format = "murmur2"
hash = "601631150"

[update]
[update.curseforge]
file-id = 3596180
project-id = 455508
release-channel = "beta"
