name = "Iris Shaders"
filename = "iris-mc1.17-1.2.0-pre.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/854/iris-mc1.17-1.2.0-pre.jar"
hash-format = "murmur2"
hash = "3926328281"

[update]
[update.curseforge]
file-id = 3612854
project-id = 455508
