name = "Krypton"
filename = "krypton-0.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/158/krypton-0.1.3.jar"
hash-format = "murmur2"
hash = "479518788"

[update]
[update.curseforge]
file-id = 3344158
project-id = 428912
release-channel = "beta"
