name = "LambDynamicLights"
filename = "lambdynamiclights-2.0.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/653/lambdynamiclights-2.0.0+1.17.jar"
hash-format = "murmur2"
hash = "1879797387"

[update]
[update.curseforge]
file-id = 3343653
project-id = 393442
release-channel = "beta"
