name = "LambdaBetterGrass"
filename = "lambdabettergrass-fabric-1.0.3+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3177/379/lambdabettergrass-fabric-1.0.3+1.16.jar"
hash-format = "murmur2"
hash = "4234188282"

[update]
[update.curseforge]
file-id = 3177379
project-id = 400322
