name = "LambdaBetterGrass"
filename = "lambdabettergrass-1.2.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3436/762/lambdabettergrass-1.2.1+1.17.jar"
hash-format = "murmur2"
hash = "3594399257"

[update]
[update.curseforge]
file-id = 3436762
project-id = 400322
release-channel = "beta"
