name = "LambDynamicLights"
filename = "lambdynamiclights-2.0.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/967/lambdynamiclights-2.0.1+1.17.jar"
hash-format = "murmur2"
hash = "1045843294"

[update]
[update.curseforge]
file-id = 3348967
project-id = 393442
release-channel = "beta"
