name = "LambDynamicLights"
filename = "lambdynamiclights-fabric-1.3.4+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3172/563/lambdynamiclights-fabric-1.3.4+1.16.jar"
hash-format = "murmur2"
hash = "3978031037"

[update]
[update.curseforge]
file-id = 3172563
project-id = 393442
release-channel = "beta"
