name = "LambdaBetterGrass"
filename = "lambdabettergrass-1.2.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/563/lambdabettergrass-1.2.0+1.17.jar"
hash-format = "murmur2"
hash = "479738688"

[update]
[update.curseforge]
file-id = 3343563
project-id = 400322
release-channel = "beta"
