name = "LambdaBetterGrass"
filename = "lambdabettergrass-1.2.2+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/355/lambdabettergrass-1.2.2+1.17.jar"
hash-format = "murmur2"
hash = "2859900242"

[update]
[update.curseforge]
file-id = 3584355
project-id = 400322
