name = "LambDynamicLights"
filename = "lambdynamiclights-2.1.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/670/lambdynamiclights-2.1.0+1.17.jar"
hash-format = "murmur2"
hash = "1361082460"

[update]
[update.curseforge]
file-id = 3541670
project-id = 393442
