name = "Litematica"
filename = "litematica-fabric-1.16.4-0.0.0-dev.20210612.170003.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/118/litematica-fabric-1.16.4-0.0.0-dev.20210612.170003.jar"
hash-format = "murmur2"
hash = "3881745574"

[update]
[update.curseforge]
file-id = 3349118
project-id = 308892
release-channel = "beta"
