name = "Litematica"
filename = "litematica-fabric-1.17.1-0.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/241/litematica-fabric-1.17.1-0.9.0.jar"
hash-format = "murmur2"
hash = "839025309"

[update]
[update.curseforge]
file-id = 3580241
project-id = 308892
