name = "Litematica"
filename = "litematica-fabric-1.17.1-0.0.0-dev.20210713.103711.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3387/62/litematica-fabric-1.17.1-0.0.0-dev.20210713.103711.jar"
hash-format = "murmur2"
hash = "3966180533"

[update]
[update.curseforge]
file-id = 3387062
project-id = 308892
release-channel = "beta"
