name = "Litematica"
filename = "litematica-fabric-1.17.0-0.0.0-dev.20210616.033538.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3353/497/litematica-fabric-1.17.0-0.0.0-dev.20210616.033538.jar"
hash-format = "murmur2"
hash = "2726499526"

[update]
[update.curseforge]
file-id = 3353497
project-id = 308892
release-channel = "beta"
