name = "Litematica"
filename = "litematica-fabric-1.17.0-0.0.0-dev.20210608.211719.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/955/litematica-fabric-1.17.0-0.0.0-dev.20210608.211719.jar"
hash-format = "murmur2"
hash = "2119924900"

[update]
[update.curseforge]
file-id = 3343955
project-id = 308892
release-channel = "beta"
