name = "Litematica"
filename = "litematica-fabric-1.17.0-0.0.0-dev.20210614.175836.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/744/litematica-fabric-1.17.0-0.0.0-dev.20210614.175836.jar"
hash-format = "murmur2"
hash = "963028034"

[update]
[update.curseforge]
file-id = 3351744
project-id = 308892
release-channel = "beta"
