name = "Litematica"
filename = "litematica-fabric-1.18.1-0.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/865/litematica-fabric-1.18.1-0.10.0.jar"
hash-format = "murmur2"
hash = "226064857"

[update]
[update.curseforge]
file-id = 3615865
project-id = 308892
release-channel = "beta"
