name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.17-0.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3354/305/lithium-fabric-mc1.17-0.7.1.jar"
hash-format = "murmur2"
hash = "3767787913"

[update]
[update.curseforge]
file-id = 3354305
project-id = 360438
release-channel = "beta"
