name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.16.5-0.6.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3215/441/lithium-fabric-mc1.16.5-0.6.4.jar"
hash-format = "murmur2"
hash = "1863285517"

[update]
[update.curseforge]
file-id = 3215441
project-id = 360438
release-channel = "beta"
