name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.16.5-0.6.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/974/lithium-fabric-mc1.16.5-0.6.6.jar"
hash-format = "murmur2"
hash = "3122352508"

[update]
[update.curseforge]
file-id = 3344974
project-id = 360438
release-channel = "beta"
