name = "MaLiLib"
filename = "malilib-fabric-1.17.1-0.10.0-dev.24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3387/61/malilib-fabric-1.17.1-0.10.0-dev.24.jar"
hash-format = "murmur2"
hash = "3959206847"

[update]
[update.curseforge]
file-id = 3387061
project-id = 303119
release-channel = "beta"
