name = "MaLiLib"
filename = "malilib-fabric-1.17.0-0.10.0-dev.22+beta.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/936/malilib-fabric-1.17.0-0.10.0-dev.22+beta.1.jar"
hash-format = "murmur2"
hash = "1145941844"

[update]
[update.curseforge]
file-id = 3343936
project-id = 303119
release-channel = "beta"
