name = "MaLiLib"
filename = "malilib-fabric-1.18.1-0.11.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3619/948/malilib-fabric-1.18.1-0.11.5.jar"
hash-format = "murmur2"
hash = "2619684835"

[update]
[update.curseforge]
file-id = 3619948
project-id = 303119
release-channel = "beta"
