name = "MiniHUD"
filename = "minihud-fabric-1.17.1-0.19.0-dev.20210707.150016.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3379/923/minihud-fabric-1.17.1-0.19.0-dev.20210707.150016.jar"
hash-format = "murmur2"
hash = "1036661412"

[update]
[update.curseforge]
file-id = 3379923
project-id = 244260
release-channel = "beta"
