name = "MiniHUD"
filename = "minihud-fabric-1.17.1-0.19.0-dev.20211027.183903.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/647/minihud-fabric-1.17.1-0.19.0-dev.20211027.183903.jar"
hash-format = "murmur2"
hash = "2705891185"

[update]
[update.curseforge]
file-id = 3542647
project-id = 244260
