name = "MiniHUD"
filename = "minihud-fabric-1.17.1-0.20.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/543/minihud-fabric-1.17.1-0.20.0.jar"
hash-format = "murmur2"
hash = "3244869042"

[update]
[update.curseforge]
file-id = 3600543
project-id = 244260
