name = "Mod Menu"
filename = "modmenu-1.16.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3479/748/modmenu-1.16.22.jar"
hash-format = "murmur2"
hash = "1537659351"

[update]
[update.curseforge]
file-id = 3479748
project-id = 308702
