name = "Mod Menu"
filename = "modmenu-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3431/313/modmenu-2.0.5.jar"
hash-format = "murmur2"
hash = "1975867466"

[update]
[update.curseforge]
file-id = 3431313
project-id = 308702
release-channel = "beta"
