name = "Mod Menu"
filename = "modmenu-2.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3441/183/modmenu-2.0.6.jar"
hash-format = "murmur2"
hash = "1040341298"

[update]
[update.curseforge]
file-id = 3441183
project-id = 308702
release-channel = "beta"
