name = "Mod Menu"
filename = "modmenu-1.16.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3211/66/modmenu-1.16.8.jar"
hash-format = "murmur2"
hash = "392405532"

[update]
[update.curseforge]
file-id = 3211066
project-id = 308702
release-channel = "beta"
