name = "Mod Menu"
filename = "modmenu-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/711/modmenu-2.0.2.jar"
hash-format = "murmur2"
hash = "36282909"

[update]
[update.curseforge]
file-id = 3348711
project-id = 308702
release-channel = "beta"
