name = "Mod Menu"
filename = "modmenu-2.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3451/992/modmenu-2.0.10.jar"
hash-format = "murmur2"
hash = "81307266"

[update]
[update.curseforge]
file-id = 3451992
project-id = 308702
release-channel = "beta"
