name = "More Chat History"
filename = "morechathistory-1.18-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/709/morechathistory-1.18-1.1.0.jar"
hash-format = "murmur2"
hash = "2459987684"

[update]
[update.curseforge]
file-id = 3545709
project-id = 518319
