name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc1.16.3-0.7.1+build.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3202/749/phosphor-fabric-mc1.16.3-0.7.1+build.11.jar"
hash-format = "murmur2"
hash = "523114946"

[update]
[update.curseforge]
file-id = 3202749
project-id = 372124
release-channel = "beta"
