name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc1.18.x-0.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3573/395/phosphor-fabric-mc1.18.x-0.8.1.jar"
hash-format = "murmur2"
hash = "535994915"

[update]
[update.curseforge]
file-id = 3573395
project-id = 372124
release-channel = "beta"
