name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc1.17.x-0.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3537/802/phosphor-fabric-mc1.17.x-0.8.0.jar"
hash-format = "murmur2"
hash = "2433894433"

[update]
[update.curseforge]
file-id = 3537802
project-id = 372124
