name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc1.16.2-0.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3537/800/phosphor-fabric-mc1.16.2-0.8.0.jar"
hash-format = "murmur2"
hash = "2011136630"

[update]
[update.curseforge]
file-id = 3537800
project-id = 372124
