name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.16.5-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/721/reeses_sodium_options-mc1.16.5-1.3.0.jar"
hash-format = "murmur2"
hash = "3650590571"

[update]
[update.curseforge]
file-id = 3596721
project-id = 511319
release-channel = "beta"
