name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.17.1-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/244/reeses_sodium_options-mc1.17.1-1.4.0.jar"
hash-format = "murmur2"
hash = "336854835"

[update]
[update.curseforge]
file-id = 3622244
project-id = 511319
