name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.17.1-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/723/reeses_sodium_options-mc1.17.1-1.3.0.jar"
hash-format = "murmur2"
hash = "1305545806"

[update]
[update.curseforge]
file-id = 3596723
project-id = 511319
