name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.16.5-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/243/reeses_sodium_options-mc1.16.5-1.4.0.jar"
hash-format = "murmur2"
hash = "2943108271"

[update]
[update.curseforge]
file-id = 3622243
project-id = 511319
release-channel = "beta"
