name = "Reload Audio Driver (RAD) [Fabric]"
filename = "reloadAudioDriver-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3342/870/reloadAudioDriver-1.0.1.jar"
hash-format = "murmur2"
hash = "1635041146"

[update]
[update.curseforge]
file-id = 3342870
project-id = 391502
release-channel = "beta"
