name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-5.12.248.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3337/658/RoughlyEnoughItems-5.12.248.jar"
hash-format = "murmur2"
hash = "2977745211"

[update]
[update.curseforge]
file-id = 3337658
project-id = 310111
release-channel = "beta"
