name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-6.0.254-alpha-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/625/RoughlyEnoughItems-6.0.254-alpha-fabric.jar"
hash-format = "murmur2"
hash = "3284613806"

[update]
[update.curseforge]
file-id = 3358625
project-id = 310111
release-channel = "beta"
