name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.3.428.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/481/RoughlyEnoughItems-7.3.428.jar"
hash-format = "murmur2"
hash = "2504803842"

[update]
[update.curseforge]
file-id = 3651481
project-id = 310111
release-channel = "beta"
