name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.3.432.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/704/RoughlyEnoughItems-7.3.432.jar"
hash-format = "murmur2"
hash = "3077402660"

[update]
[update.curseforge]
file-id = 3652704
project-id = 310111
release-channel = "beta"
