name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-5.11.202.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3272/771/RoughlyEnoughItems-5.11.202.jar"
hash-format = "murmur2"
hash = "2823046903"

[update]
[update.curseforge]
file-id = 3272771
project-id = 310111
release-channel = "beta"
