name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-6.0.267-alpha-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3411/641/RoughlyEnoughItems-6.0.267-alpha-fabric.jar"
hash-format = "murmur2"
hash = "2578121980"

[update]
[update.curseforge]
file-id = 3411641
project-id = 310111
release-channel = "beta"
