name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.2.425.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/571/RoughlyEnoughItems-7.2.425.jar"
hash-format = "murmur2"
hash = "2923612275"

[update]
[update.curseforge]
file-id = 3638571
project-id = 310111
release-channel = "beta"
