name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-6.3.391.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/25/RoughlyEnoughItems-6.3.391.jar"
hash-format = "murmur2"
hash = "3942054131"

[update]
[update.curseforge]
file-id = 3612025
project-id = 310111
