name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-7.1.361.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3603/234/RoughlyEnoughItems-7.1.361.jar"
hash-format = "murmur2"
hash = "1756015048"

[update]
[update.curseforge]
file-id = 3603234
project-id = 310111
release-channel = "beta"
