name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-6.0.251-alpha-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/599/RoughlyEnoughItems-6.0.251-alpha-fabric.jar"
hash-format = "murmur2"
hash = "2683460052"

[update]
[update.curseforge]
file-id = 3351599
project-id = 310111
release-channel = "beta"
