name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-8.2.461.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "712a733709aed0d38c476bdd72555bcb123aa6d5"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3799027
project-id = 310111
