name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-7.1.357.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/798/RoughlyEnoughItems-7.1.357.jar"
hash-format = "murmur2"
hash = "1008832581"

[update]
[update.curseforge]
file-id = 3580798
project-id = 310111
release-channel = "beta"
