name = "Server Tick"
filename = "servertick-mc1.18-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/454/servertick-mc1.18-1.6.jar"
hash-format = "murmur2"
hash = "1098068381"

[update]
[update.curseforge]
file-id = 3542454
project-id = 402240
release-channel = "beta"
