name = "Server Tick"
filename = "servertick-mc1.18-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/454/servertick-mc1.18-1.6.jar"
hash-format = "sha1"
hash = "13f2ef00ba465ceaa0c7046e4a9fcb7b28311854"

[update]
[update.curseforge]
file-id = 3542454
project-id = 402240
