name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-3.0.7+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3709/224/shulkerboxtooltip-3.0.7+1.18.2.jar"
hash-format = "sha1"
hash = "f95516b16b83a204ea5f5c21856d1d982a773765"

[update]
[update.curseforge]
file-id = 3709224
project-id = 315811
