name = "Sodium Extra"
filename = "sodium-extra-0.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3287/182/sodium-extra-0.2.5.jar"
hash-format = "murmur2"
hash = "4283682161"

[update]
[update.curseforge]
file-id = 3287182
project-id = 447673
release-channel = "beta"
