name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3392/192/sodium-extra-mc1.17.1-0.3.3.jar"
hash-format = "murmur2"
hash = "105773225"

[update]
[update.curseforge]
file-id = 3392192
project-id = 447673
release-channel = "beta"
