name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3528/157/sodium-extra-mc1.17.1-0.3.6.jar"
hash-format = "murmur2"
hash = "3449763978"

[update]
[update.curseforge]
file-id = 3528157
project-id = 447673
release-channel = "beta"
