name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.3.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/799/sodium-extra-mc1.17.1-0.3.9.jar"
hash-format = "murmur2"
hash = "4073840555"

[update]
[update.curseforge]
file-id = 3623799
project-id = 447673
