name = "Sodium Extra"
filename = "sodium-extra-0.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3318/971/sodium-extra-0.3.0.jar"
hash-format = "murmur2"
hash = "921037557"

[update]
[update.curseforge]
file-id = 3318971
project-id = 447673
release-channel = "beta"
