name = "Sodium Extra"
filename = "sodium-extra-mc1.16.5-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/88/sodium-extra-mc1.16.5-0.4.0.jar"
hash-format = "sha1"
hash = "b1d62c055cd7f1271772322235c685058555b0fa"

[update]
[update.curseforge]
file-id = 3652088
project-id = 447673
