name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/91/sodium-extra-mc1.17.1-0.4.0.jar"
hash-format = "sha1"
hash = "5a8ead439b9dba43fe9fe26936d8b022d398dce8"

[update]
[update.curseforge]
file-id = 3652091
project-id = 447673
