name = "Sodium Extra"
filename = "sodium-extra-0.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3355/671/sodium-extra-0.3.2.jar"
hash-format = "murmur2"
hash = "2026782759"

[update]
[update.curseforge]
file-id = 3355671
project-id = 447673
release-channel = "beta"
