name = "Sodium Extra"
filename = "sodium-extra-mc1.18.1-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/95/sodium-extra-mc1.18.1-0.4.0.jar"
hash-format = "murmur2"
hash = "3776589453"

[update]
[update.curseforge]
file-id = 3652095
project-id = 447673
release-channel = "beta"
