name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3442/217/sodium-extra-mc1.17.1-0.3.4.jar"
hash-format = "murmur2"
hash = "3796699782"

[update]
[update.curseforge]
file-id = 3442217
project-id = 447673
release-channel = "beta"
