name = "Sodium Extra"
filename = "sodium-extra-mc1.18.1-0.3.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/805/sodium-extra-mc1.18.1-0.3.9.jar"
hash-format = "murmur2"
hash = "707950928"

[update]
[update.curseforge]
file-id = 3623805
project-id = 447673
release-channel = "beta"
