name = "Sodium"
filename = "sodium-fabric-mc1.17.1-0.3.4+build.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/275/sodium-fabric-mc1.17.1-0.3.4+build.13.jar"
hash-format = "murmur2"
hash = "686429752"

[update]
[update.curseforge]
file-id = 3605275
project-id = 394468
