name = "Sodium Extra"
filename = "sodium-extra-mc1.18-0.3.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/997/sodium-extra-mc1.18-0.3.7.jar"
hash-format = "murmur2"
hash = "38126557"

[update]
[update.curseforge]
file-id = 3542997
project-id = 447673
release-channel = "beta"
