name = "Sodium"
filename = "sodium-fabric-mc1.17.1-0.3.3+build.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3535/40/sodium-fabric-mc1.17.1-0.3.3+build.8.jar"
hash-format = "murmur2"
hash = "130037644"

[update]
[update.curseforge]
file-id = 3535040
project-id = 394468
