name = "Sodium"
filename = "sodium-fabric-mc1.16.5-0.2.0+build.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3488/820/sodium-fabric-mc1.16.5-0.2.0+build.4.jar"
hash-format = "murmur2"
hash = "706367559"

[update]
[update.curseforge]
file-id = 3488820
project-id = 394468
