name = "Sodium Extra"
filename = "sodium-extra-mc1.16.5-0.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3517/166/sodium-extra-mc1.16.5-0.3.5.jar"
hash-format = "murmur2"
hash = "1805212549"

[update]
[update.curseforge]
file-id = 3517166
project-id = 447673
