name = "Sodium Extra"
filename = "sodium-extra-mc1.18.1-0.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/328/sodium-extra-mc1.18.1-0.3.8.jar"
hash-format = "murmur2"
hash = "4216081621"

[update]
[update.curseforge]
file-id = 3605328
project-id = 447673
release-channel = "beta"
