name = "Sodium Extra"
filename = "sodium-extra-0.4.4+mc1.18.2-build.39.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "a171437b0a8df4ba89015eff4f97504220577f34"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3793985
project-id = 447673
