name = "Sodium Extra"
filename = "sodium-extra-mc1.16.5-0.3.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/798/sodium-extra-mc1.16.5-0.3.9.jar"
hash-format = "murmur2"
hash = "2480128637"

[update]
[update.curseforge]
file-id = 3623798
project-id = 447673
