name = "Transparent (Fabric)"
filename = "transparent-2.1.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3179/349/transparent-2.1.0-fabric.jar"
hash-format = "murmur2"
hash = "4267665372"

[update]
[update.curseforge]
file-id = 3179349
project-id = 377582
release-channel = "beta"
