name = "Tweakeroo"
filename = "tweakeroo-fabric-1.17.1-0.11.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/869/tweakeroo-fabric-1.17.1-0.11.0.jar"
hash-format = "murmur2"
hash = "341977942"

[update]
[update.curseforge]
file-id = 3579869
project-id = 297344
release-channel = "beta"
