name = "Tweakeroo"
filename = "tweakeroo-fabric-1.17.0-0.10.0-dev.20210608.211857.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/945/tweakeroo-fabric-1.17.0-0.10.0-dev.20210608.211857.jar"
hash-format = "murmur2"
hash = "2544603135"

[update]
[update.curseforge]
file-id = 3343945
project-id = 297344
release-channel = "beta"
