name = "Tweakeroo"
filename = "tweakeroo-fabric-1.17.0-0.10.0-dev.20210614.173711.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/747/tweakeroo-fabric-1.17.0-0.10.0-dev.20210614.173711.jar"
hash-format = "murmur2"
hash = "3135753917"

[update]
[update.curseforge]
file-id = 3351747
project-id = 297344
release-channel = "beta"
