name = "Tweakeroo"
filename = "tweakeroo-fabric-1.16.5-0.10.0-dev.20210917.191839.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/587/tweakeroo-fabric-1.16.5-0.10.0-dev.20210917.191839.jar"
hash-format = "murmur2"
hash = "175495128"

[update]
[update.curseforge]
file-id = 3542587
project-id = 297344
release-channel = "beta"
