name = "Tweakeroo"
filename = "tweakeroo-fabric-1.18.0-0.11.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/871/tweakeroo-fabric-1.18.0-0.11.0.jar"
hash-format = "murmur2"
hash = "701146697"

[update]
[update.curseforge]
file-id = 3579871
project-id = 297344
release-channel = "beta"
