name = "Tweakeroo"
filename = "tweakeroo-fabric-1.18.1-0.12.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/870/tweakeroo-fabric-1.18.1-0.12.0.jar"
hash-format = "murmur2"
hash = "1839671098"

[update]
[update.curseforge]
file-id = 3615870
project-id = 297344
release-channel = "beta"
