name = "WTHIT"
filename = "wthit-fabric-4.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/10/wthit-fabric-4.8.0.jar"
hash-format = "sha1"
hash = "e340f9f3752f881ce71599c8675d0bed9bfc2eb7"

[update]
[update.curseforge]
file-id = 3707010
project-id = 440979
