name = "WTHIT"
filename = "wthit-fabric-4.9.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3771/780/wthit-fabric-4.9.1.jar"
hash-format = "sha1"
hash = "c0304d46a9d3afbe4432f77b028ab9f0469f9c2b"

[update]
[update.curseforge]
file-id = 3771780
project-id = 440979
