name = "WTHIT"
filename = "wthit-fabric-4.10.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "014f61ffa930eaf41dd48156e97dde63abe08327"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3791303
project-id = 440979
