name = "WTHIT"
filename = "wthit-fabric-4.10.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3780/925/wthit-fabric-4.10.1.jar"
hash-format = "sha1"
hash = "73e1fc50286a55c05cee837a8b93ef28a05fd04f"

[update]
[update.curseforge]
file-id = 3780925
project-id = 440979
