name = "WTHIT"
filename = "wthit-fabric-4.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/650/wthit-fabric-4.7.3.jar"
hash-format = "sha1"
hash = "89cf307b6d8ae9c84e6ba3816b3d5d3c386e48e5"

[update]
[update.curseforge]
file-id = 3680650
project-id = 440979
