name = "Xaero's World Map"
filename = "XaerosWorldMap_1.22.0_Fabric_1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "d6f7ff3830a3169a3e0d33045fed060b219af4b2"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3796748
project-id = 317780
