name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.3.1_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/988/XaerosWorldMap_1.20.3.1_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "1214207207"

[update]
[update.curseforge]
file-id = 3646988
project-id = 317780
