name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.0_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/296/XaerosWorldMap_1.20.0_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "2594899038"

[update]
[update.curseforge]
file-id = 3613296
project-id = 317780
